#
# Docker Compose with MySQL Server and phpMyAdmin
#
#
version: '3'
services:
  db:
    build:
      context: docker/db
    image: bicycle/db
    container_name: bicycle_db
    volumes:
      - ./var/mysql/data:/app/data
    ports:
      - "20306:3306"
    env_file:
      - docker-compose.env
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bicycle_admin
    ports:
      - "20008:80"
    links:
      - db:db
    env_file:
      - docker-compose.env
